# Generated by Django 4.2.4 on 2023-08-28 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_group_id_member_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='fine_details',
        ),
        migrations.AddField(
            model_name='contribution',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='interest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='loanfunding',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
